source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/hacoma/iOS-Hacoma-Module-CocoaPods-Specs.git'
source 'https://github.com/hacoma/Synstagram-Module-CocoaPods-Specs.git'

platform :ios, '11.0'
project 'LoginScene'
inhibit_all_warnings!
use_frameworks!

def hacomaExtensions
    pod 'HacomaExtensions', '1.0.2'
end

def hacomaUI
    pod 'HacomaUI/InsetTextField', '1.0.2'
end

def apiService
    pod 'APIService/Auth', '1.0.2'
end

target :'LoginScene' do
    hacomaExtensions
    hacomaUI
    apiService
end