source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/hacoma/iOS-Hacoma-Module-CocoaPods-Specs.git'
source 'https://github.com/hacoma/Synstagram-Module-CocoaPods-Specs.git'

platform :ios, '11.0'
project 'LoginScene'
inhibit_all_warnings!
use_frameworks!

def hacomaDIConatiner
    pod 'HacomaDIContainer', '1.0.4'
end

def hacomaExtensions
    pod 'HacomaExtensions', '1.0.2'
end

def hacomaUI
    pod 'HacomaUI/InsetTextField', '1.0.2'
end

def apiService
    pod 'APIService/Auth', '1.0.5'
end

def dependency
    pod 'Dependencies/Login', '1.0.2'
    pod 'Dependencies/AlbumList', '1.0.2'
end

target :'LoginScene' do
    hacomaDIConatiner
    hacomaExtensions
    hacomaUI
    apiService
    dependency
end