//
//  LoginPresenter.swift
//  synstagram-scene-login
//
//  Created by hacoma on 2020/10/09.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol LoginPresentationLogic {
    
    func showLoadingView()
    func hideLoadingView()
    
    func presentAlbumList(entity: LoginModel.Response.Entity)
    func presentError(error: LoginModel.Response.Error)
}

final class LoginPresenter: LoginPresentationLogic {
    
    weak var viewController: LoginDisplayLogic?
    
    func showLoadingView() {
        viewController?.showLoadingView()
    }
    
    func hideLoadingView() {
        viewController?.hideLoadingView()
    }
    
    func presentAlbumList(entity: LoginModel.Response.Entity) {
        let viewModel = LoginModel.ViewModel.AlbumToken(username: entity.username)
        viewController?.displayAlbumList(viewModel: viewModel)
    }
    
    func presentError(error: LoginModel.Response.Error) {
        let viewModel = LoginModel.ViewModel.Error(message: error.message)
        viewController?.displayError(viewModel: viewModel)
    }
}
