//
//  LoginRouter.swift
//  synstagram-scene-login
//
//  Created by hacoma on 2020/10/09.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import Dependencies
import HacomaDIContainer

protocol LoginRoutingLogic {
    
    func routeToAlbumList(username: String)
}

final class LoginRouter: NSObject, LoginRoutingLogic {
    
    weak var viewController: LoginViewController?
    
    @Injectable
    private var albumListDependency: AlbumListDependency?
    
    func routeToAlbumList(username: String) {
        let albumListVC = albumListDependency?.getViewController(username: username)
        albumListVC?.view.backgroundColor = .red
        
        let keyWindow = UIApplication.shared.windows.first { $0.isKeyWindow }
        keyWindow?.rootViewController = albumListVC
    }
}
