//
//  LoginRouter.swift
//  synstagram-scene-login
//
//  Created by hacoma on 2020/10/09.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol LoginRoutingLogic {
    
    func routeToAlbumList(username: String)
}

final class LoginRouter: NSObject, LoginRoutingLogic {
    
    weak var viewController: LoginViewController?
    
    private var routingDependency: RoutingDependency? {
        return viewController?.dependencies?.routingDependency
    }
    
    func routeToAlbumList(username: String) {
        routingDependency?.routeToAlbumList(username: username)
    }
}
